import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import toolsRouter from "./tools";
import vaultRouter from "./vault";
import leaderboardRouter from "./leaderboard";
import broadcastRouter from "./broadcast";
import settingsRouter from "./settings";
import telemetryRouter from "./telemetry";
import aiRouter from "./ai";
import emailRoutingRouter from "./email-routing";
import telegramRouter from "./telegram";
import emailAccountsRouter from "./email-accounts";
import emailComposeRouter from "./email-compose";
import supportRouter from "./support";
import referralsRouter from "./referrals";
import eventsRouter from "./events";
import emailRouter from "./email";
import walletsRouter from "./wallets";
import logsRouter from "./logs";
import pluginsRouter from "./plugins";
import subscriptionsRouter from "./subscriptions";
import paymentsRouter from "./payments";
import creditsRouter from "./credits";
import telemetryStreamRouter from "./telemetry-stream";
import localAccountsRouter from "./local-accounts";
import messagesRouter from "./messages";
import aiActionsRouter from "./ai-actions";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(eventsRouter);
router.use(logsRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(emailRouter);
router.use(walletsRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(toolsRouter);
router.use(vaultRouter);
router.use(leaderboardRouter);
router.use(broadcastRouter);
router.use(settingsRouter);
router.use(pluginsRouter);
router.use(telemetryRouter);
router.use(aiRouter);
router.use(emailRoutingRouter);
router.use(telegramRouter);
router.use(emailAccountsRouter);
router.use(emailComposeRouter);
router.use(supportRouter);
router.use(referralsRouter);
router.use(subscriptionsRouter);
router.use(paymentsRouter);
router.use(creditsRouter);
router.use(telemetryStreamRouter);
router.use(localAccountsRouter);
router.use(messagesRouter);
router.use(aiActionsRouter);
router.use(notificationsRouter);

export default router;
