import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import toolsRouter from "./tools";
import vaultRouter from "./vault";
import leaderboardRouter from "./leaderboard";
import broadcastRouter from "./broadcast";
import settingsRouter from "./settings";
import telemetryRouter from "./telemetry";
import aiRouter from "./ai";
import emailRoutingRouter from "./email-routing";
import telegramRouter from "./telegram";
import emailAccountsRouter from "./email-accounts";
import supportRouter from "./support";
import referralsRouter from "./referrals";
import eventsRouter from "./events";
import emailRouter from "./email";

const router: IRouter = Router();

router.use(eventsRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(emailRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(toolsRouter);
router.use(vaultRouter);
router.use(leaderboardRouter);
router.use(broadcastRouter);
router.use(settingsRouter);
router.use(telemetryRouter);
router.use(aiRouter);
router.use(emailRoutingRouter);
router.use(telegramRouter);
router.use(emailAccountsRouter);
router.use(supportRouter);
router.use(referralsRouter);

export default router;
